# current working directory
DIR	= ecologylab/types

JAVA_SRC = Type.java TypeRegistry.java BooleanType.java ByteType.java CharType.java ColorType.java DoubleType.java FloatType.java IntType.java LongType.java ShortType.java StringType.java URLType.java

JAVA_ROOT= ../../

MAKE_DIR = ../../../../makefiles
include $(MAKE_DIR)/applets.make

cabsign: all

nsjar: all

sunjar: all

