# current working directory
DIR	= ecologylab/xml

JAVA_SRC = CharacterConstants.java
# XmlTools.java ElementState.java 

JAVA_ROOT= ../../

MAKE_DIR = ../../../../makefiles
include $(MAKE_DIR)/applets.make

cabsign: all

nsjar: all

sunjar: all

