# current working directory
DIR	= ecologylab/xml

JAVA_SRC = CharacterConstants.java IO.java XmlTranslationException.java \
	XmlTools.java ElementState.java XMLTranslationConfig.java

JAVA_ROOT= ../../

MAKE_DIR = ../../../../makefiles
include $(MAKE_DIR)/applets.make

cabsign: all

nsjar: all

sunjar: all

